### ISSUE TITLE
Scrollbar Not Rendering

### ISSUE THREAD

**Issue by ackramer** [hetima/DSP_PlanetFinder#12]
Title indicates the issue, cannot scroll. Running on 4k monitor.

![image](https://github.com/user-attachments/assets/4607fc2e-01e6-4471-adeb-2abdcb3a5569)

**Comment by hetima** [comment]
fixed in 1.1.5
thanks

**Comment by ackramer** [comment]
sweet, thanks for the quick fix @hetima
