### ISSUE TITLE
Regarding power discharge 

### ISSUE THREAD

**Issue by starfi5h** [hetima/DSP_PlanetFinder#3]
PlanetFinder doesn't take accumulators discharge power into calculation
![discharge](https://user-images.githubusercontent.com/50672801/175188623-a25fc7d4-b79c-4af7-af55-789f689fe023.jpg)
Consider adding discharge power into total power generation, or show its value separately?

**Comment by hetima** [comment]
Supported in 0.4.2
I don't use it in my main game, so I'm not sure if it is appropriate.

**Comment by starfi5h** [comment]
Yes, this solves the issue. Thanks!
