### ISSUE TITLE
Feature Request: search box or Filter

### ISSUE THREAD

**Issue by MactasticMendez** [hetima/DSP_PlanetFinder#4]
An option to type multiple resources in a search box of select multiple resources and it show you which planets have all the selected resources then hover on the planet listed to show number of veins of the searched for resources.

**Comment by hetima** [comment]
Multiple resources selection is already built-in by shift-clicking resource icon.

And press tab key to toggle the display among selected resources.
The viewability is not high enough as it is. I'd like to do something about this, but have no plans yet.

**Comment by mikeloeven** [comment]
i would also like to just search by name as well that way you can tag your factory worlds and pull it up by entering a short partial search string

**Comment by hetima** [comment]
Yes, that would be the next milestone.

**Comment by hetima** [comment]
Name search has been added in v1.0.0
