### ISSUE TITLE
Feature Request: reduce RAM usage

### ISSUE THREAD

**Issue by starfi5h** [hetima/DSP_PlanetFinder#5]
As the video shows, after PlanetFinder loaded 240 planets, the memory usage increase by 1.1GB.  
If user uses mods like GalacticScale to increase number of planets, it will consume massive RAM. 

https://user-images.githubusercontent.com/50672801/233209915-6ba6a1c9-cd80-4e63-901e-5fff2559b164.mp4

Resource Spreadsheet Generator mod avoids this issue by freeing planet data after calculating is done, and caching the results (in `planetResourceData`) so it doesn't have to recalculate again.
https://github.com/GreyHak/dsp-csv-gen/blob/master/DSPSpreadsheetGenMod.cs#L408-L413

**Comment by hetima** [comment]
Thanks for the solution tip.
I will try it.

**Comment by hetima** [comment]
Probably improved in 1.0.1

**Comment by starfi5h** [comment]
The issue is solved in 1.0.1. Thank you!
