### ISSUE TITLE
[Feature Request] Add a filter for Tidally Locked planets

### ISSUE THREAD

**Issue by wrossmann** [hetima/DSP_PlanetFinder#8]
While it's great that planets are marked as tidally locked it would be nice if we could search for them directly via a clickable filter.

Thanks

**Comment by hetima** [comment]
### v1.1.3
- Tidal locked or gas giant planets can be name searched by typing `[TL]` or `[GAS]`.

**Comment by wrossmann** [comment]
TIL.
