### ISSUE TITLE
Unlock Universe Exploration 4,Still can't use this function

### ISSUE THREAD

**Issue by yegetables** [hetima/DSP_PlanetFinder#9]
![无标题2](https://github.com/hetima/DSP_PlanetFinder/assets/37119488/614ce4ab-55c8-455c-913c-99a4ada45a8b)

**Comment by hetima** [comment]
![4](https://github.com/hetima/DSP_PlanetFinder/assets/33700/7c7ec281-9eec-4bf4-9688-84f47d4a5d04)
